name: build-bless
on:
  workflow_dispatch:
  push:
    paths:
      - 'bless.py'
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          pip install pyinstaller
          pyinstaller -F -n 祝福程序 bless.py
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: bless-exe
          path: dist/祝福程序.exe
